build site:
  image: node:11.13.0-alpine
  stage: build
  only:
    - master
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

deploy:
  image: node:11.13.0-alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort 122\n\tHostKeyAlgorithms=+ssh-dss\n\tPubkeyAcceptedKeyTypes ssh-dss\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ gitlab@travel.iteora.com:/home/gitlab/booking-tours-front-2
